/** English UI catalog — source of truth for TranslationDictionary. */

export const en = {
  common: {
    confirm: "Confirm",
    cancel: "Cancel",
    retry: "Retry",
    ok: "OK",
    send: "Send",
    loading: "Loading",
    copied: "Copied",
    copyMeetLink: "Copy Meet link",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    meeting: "Meeting",
    close: "Close",
  },
  sidebar: {
    language: "Language",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  greeting: {
    headline: "Hey! Kacper's AI assistant here.",
    hints: {
      ask: "Ask anything about Kacper",
      book: "Book a meeting",
      contact: "Contact Kacper directly",
    },
  },
  chat: {
    placeholder: "Ask anything…",
    loadingChat: "Loading chat",
    loadingOlder: "Loading older messages",
    assistantThinking: "Assistant is thinking…",
    scrollUpOlder: "Scroll up for older messages",
    errorGeneric: "Something went wrong. Please try again.",
    messageTooLong: "Message cannot be longer than {{length}} characters.",
    stopResponse: "Stop response",
    endVoice: "End voice conversation",
    startVoice: "Start voice conversation",
    startListening: "Start speaking",
    sendVoiceTurn: "Send voice message",
    exitToText: "Switch to text chat",
    voiceLoading: "Connecting voice…",
    agentThinking: "Assistant is thinking",
    voiceEmptyTurn: "No speech detected — tap the mic to try again.",
    voiceSomethingWentWrong: "Something went wrong with voice. Try again or switch to text.",
    voiceThinkingTooLong: "Sorry, the Assistant was thinking for too long.",
    sendMessage: "Send message",
    enableAudio: "Enable audio",
    interrupted: "Interrupted before finishing",
    lengthTruncated: "Utterance cut — maximum length reached",
    voiceLanguageLabel: "Voice language",
    aiTermsNotice:
      "By using the chat, you accept the <termsLink>Terms</termsLink>.",
  },
  terms: {
    title: "Terms of use",
    backToChat: "Back to chat",
    updated: "Last updated: 3 August 2026",
    intro:
      "These terms apply to this personal website and the AI chat assistant available on it. By using the chat (text or voice), you agree to them.",
    sections: {
      service: {
        title: "What this service is",
        body: "The assistant is an experimental AI demo on my personal site. It can answer questions about me, help book a meeting, or relay a private message. It is not a commercial product, not a substitute for talking to me directly, and not continuous professional support.",
      },
      ai: {
        title: "AI-generated answers",
        body: "Chat and voice replies are generated by artificial intelligence. They may be incomplete, outdated, or wrong. Always verify important facts before relying on them.",
      },
      noAdvice: {
        title: "No professional advice",
        body: "Nothing the assistant says is legal, medical, financial, or other professional advice. Do not treat replies as instructions for decisions with legal, health, or financial consequences.",
      },
      liability: {
        title: "Responsibility",
        body: "I do not guarantee that answers are accurate, complete, or fit for any purpose. To the fullest extent permitted by law, I am not liable for decisions, actions, or losses arising from use of the assistant or reliance on its output.",
      },
      data: {
        title: "Data and sessions",
        body: "Using the chat creates a session and may store conversation content needed to run the service (including booking or contact details you provide). Do not submit sensitive personal data you are not comfortable sharing. Abuse, spam, or attempts to disrupt the service may result in access being limited or paused.",
      },
      changes: {
        title: "Changes",
        body: "I may update these terms or pause public access at any time. Continued use of the chat after changes means you accept the updated terms.",
      },
    },
  },
  voice: {
    ttsFallbackWarning:
      "Voice replies in this language are not supported yet. The agent will answer in English.",
  },
  pause: {
    title: "Assistant paused",
    defaultMessage:
      "Due to high interest, access to the assistant is temporarily paused.",
  },
  invite: {
    invalidTitle: "Invalid invitation",
    invalidBody:
      "This invitation link is invalid, expired, or has already been used up. You can continue as a regular visitor.",
  },
  rateLimit: {
    title: "Limit reached",
    bodyChat:
      "You've reached the chat message limit. You can try again in {{time}}.",
    bodyVoice:
      "You've reached the voice message limit. You can try again in {{time}}.",
    bodyDirectMessage:
      "You've reached the private message limit. You can try again in {{time}}.",
    bodyEdge:
      "Too many requests from your network. You can try again in {{time}}.",
    tryAgainNow: "You can try again now.",
    understand: "I understand",
  },
  turnstile: {
    verifyNew: "We need to verify you are human to continue.",
    verifyExpired:
      "Session expired. We need to verify you are human to continue.",
    verificationFailed: "Verification failed. Please try again.",
    securityVerification: "Security verification",
  },
  language: {
    changeFailed: "Could not update language. Please try again.",
  },
  systemNotes: {
    booking: {
      confirmed: 'Booking "{{name}}" confirmed',
      cancelled: 'Booking "{{name}}" cancelled',
    },
    meeting: {
      cancelled: 'Meeting "{{name}}" cancelled',
    },
    cancellation: {
      aborted: 'Cancellation of "{{name}}" aborted',
    },
    private: {
      message_sent:
        "Private message sent from {{name}} ({{email}}): {{message}}",
      message_cancelled: "Private message cancelled",
    },
  },
  booking: {
    otpTitle: "Enter confirmation code",
    otpSent: "Code sent to {{email}}. Expires in {{timer}}.",
    otpAria: "Booking confirmation code",
    codeExpired: "Confirmation code expired.",
    tooManyAttempts: "Too many incorrect attempts.",
    slotUnavailable: "That time slot is no longer available.",
    incorrectCode: "Incorrect code. Try again.",
    confirmFailed: "Could not confirm the booking.",
    cancelled: "Booking cancelled.",
    cancelFailed: "Could not cancel the booking.",
    successTitle: "Meeting confirmed",
    successDescription:
      "An invitation was sent to {{email}}. The meeting should already be in your calendar — check your inbox if you do not see it yet.",
    joinMeet: "Join with Google Meet",
    downloadInvite: "Download the invitation",
    backupInviteHint:
      "Backup option — only if the invite did not appear in your calendar.",
    inviteTooltip:
      "If the meeting was not added to your calendar automatically, open this file to add it manually (works with Google Calendar, Outlook, and Apple Calendar).",
    aboutDownload: "About downloading the invitation",
  },
  cancellation: {
    title: "Cancel meeting",
    otpSent: "Code sent to {{email}}. Expires in {{timer}}.",
    codeExpired: "Cancellation code expired.",
    tooManyAttempts: "Too many incorrect attempts.",
    incorrectCode: "Incorrect code. Try again.",
    cancelFailed: "Could not cancel the meeting.",
    cancelled: "Meeting cancelled.",
    aborted: "Cancellation aborted.",
    abortFailed: "Could not abort cancellation.",
    confirmCancel: "Confirm cancel",
    keepMeeting: "Keep meeting",
    emailSuppressed:
      "This email cannot receive codes. Use a different address or contact the host.",
    cannotCancel: "That meeting can no longer be cancelled.",
    startFailed: "Could not start cancellation.",
  },
  meetings: {
    upcomingAria: "Your upcoming meetings",
    noUpcoming: "No upcoming meetings in this session.",
    details: "Details",
    detailsTitle: "Meeting details",
    startsIn: "Starts in",
    started: "This meeting has started.",
    countdownDays:
      "{{days}} days, {{hours}} hours, {{minutes}} minutes, {{seconds}} seconds remaining",
    countdownShort:
      "{{hours}} hours, {{minutes}} minutes, {{seconds}} seconds remaining",
    countdownMin: "Min",
    countdownSec: "Sec",
    noMeetLink: "No Google Meet link is available for this meeting.",
    cancelMeeting: "Cancel meeting",
  },
  directMessage: {
    formAria: "Private message form",
    title: "Send a private message",
    description:
      "Your message goes directly to the owner. Phone is optional.",
    name: "Name",
    email: "Email",
    phoneOptional: "Phone number (optional)",
    message: "Message",
    placeholder: "Write your message…",
    sent: "Private message sent.",
    sendFailed: "Could not send the message.",
    cancelled: "Message cancelled.",
    cancelFailed: "Could not cancel the message form.",
    errors: {
      nameRequired: "Name is required.",
      nameMax: "Name must be at most {{max}} characters.",
      emailInvalid: "Enter a valid email address.",
      phoneInvalid: "Enter a valid phone number.",
      messageLength: "Message must be {{min}}–{{max}} characters.",
    },
  },
} as const;

/** Nested string leaves matching the English catalog shape. */
type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]>;
};

export type TranslationDictionary = DeepStringify<typeof en>;
